# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/05_bucket_sort.ipynb (unless otherwise specified).

__all__ = ['bucket_sort']

# Cell

def bucket_sort(a):
    if not a:
        return a

    # O(n)
    k = max(a)+1
    # O(k)
    c = [0] * k

    # O(n)
    for i in a:
        c[i] += 1

    p = 0
    for i, cnt in enumerate(c):
        for j in range(cnt):
            a[p] = i
            p += 1
    return a