# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/04_count_sort.ipynb (unless otherwise specified).

__all__ = ['counting_sort']

# Cell

def counting_sort(a):
    if not a:
        return a

    # O(n)
    k = max(a)+1
    sz = len(a)
    # O(k)
    c = [0] * k
    # O(n)
    b = [0] * sz

    # O(n)
    for i in a:
        c[i] += 1

    for i in range(1, k):
        c[i] += c[i-1]

    for i in a:
        c[i] -= 1
        p = c[i]
        b[p] = i
    return b