# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_heap.ipynb (unless otherwise specified).

__all__ = ['left', 'right', 'parent', 'heapify', 'heap_down', 'heap_up']

# Cell

def left(i):
    return (i << 1) + 1


def right(i):
    return (i << 1) + 2


def parent(i):
    return (i-1)>>1


def _swap(a, i, sz):
    if i >= sz:
        return

    l = left(i)
    smallest = i
    if l < sz and a[l] < a[i]:
        smallest = l

    r = right(i)
    if r < sz and a[r] < a[smallest]:
        smallest = r
    if smallest != i:
        a[i], a[smallest] = a[smallest], a[i]


def heapify(a):
    sz = len(a)
    n = (len(a)//2)-1
    for i in range(n, -1, -1):
        _swap(a, i, sz)


# assume heap is already built
def heap_down(a, i, sz):
    if i >= sz:
        return

    l = left(i)
    r = right(i)

    #which branch
    s = l
    if (r < sz) and (a[r] < a[b]):
        s = r

    if (s < sz) and (a[i] > a[s]):
        a[i], a[b] = a[b], a[i]
        heap_down(a, b, sz)


# assume heap is already built
def heap_up(a, i):
    while i > 0:
        p = parent(i)
        if a[i] >= a[p]:
            break

        a[p], a[i] = a[i], a[p]
        i = p

