# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DisjointSet": "00_disjoint_set.ipynb",
         "left": "01_heap.ipynb",
         "right": "01_heap.ipynb",
         "parent": "01_heap.ipynb",
         "naive_heapify": "01_heap.ipynb",
         "naive_heap_down": "01_heap.ipynb",
         "heapify": "01_heap.ipynb"}

modules = ["core/ds/disjointset.py",
           "core/ds/heap.py"]

doc_url = "https://blackcherry88.github.io/algorithm/"

git_url = "https://github.com/blackcherry88/algorithm/tree/master/"

def custom_doc_links(name): return None
