# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DisjointSet": "00_disjoint_set.ipynb"}

modules = ["core/utils.py"]

doc_url = "https://blackcherry88.github.io/algorithm/"

git_url = "https://github.com/blackcherry88/algorithm/tree/master/"

def custom_doc_links(name): return None
